name: Update Versions

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install NPM dependencies
      run: npm ci

    - name: Fetch versions
      run: npm run fetchVersions

    - name: Commit changes
      run: |
        if [[ -n $(git status -s) ]]
        then
          git config --global user.name 'openui5bot'
          git config --global user.email 'openui5@sap.com'
          git commit -am "Automatic versions update"
          git push
        else
          echo "NO CHANGES! SKIPPING COMMIT & PUSH!"
        fi
